### ISSUE TITLE
Path rendering

### ISSUE THREAD

**Issue by doublex** [meyfa/php-svg#100] opened 2020-10-12 15:30 UTC
This SVG should render a hole.
Thanks a lot + best wishes

````
$svg = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 5 5"><path d="M0 0 H5 V5 H0z M1 1 V4 H4 V1z" fill="#ff0000"/></svg>';
$image = SVG::fromString( $svg );
$doc = $image->getDocument();
$gd = $image->toRasterImage( 512, 512 );
imagepng( $gd, '/tmp/svg.png', 0 );
imagedestroy( $gd );
````

**Comment by meyfa** [comment] 2020-10-12 16:15
Duplicate of #28

**Closed by meyfa** 2020-10-12 16:15 UTC
